/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/everest/karamel/krml LongSubtraction.fst -add-include <immintrin.h> -skip-compilation
  F* version: <unknown>
  KaRaMeL version: 442927db
 */

#include "LongSubtraction.h"

uint8_t LongSubtraction_sub(uint64_t *dst, uint64_t *x, uint64_t *y, uint8_t b0)
{
  uint64_t *dst0 = dst;
  uint64_t *dst1 = dst + 1U;
  uint64_t *dst2 = dst + 2U;
  uint64_t *dst3 = dst + 3U;
  uint64_t *x0 = x;
  uint64_t *x1 = x + 1U;
  uint64_t *x2 = x + 2U;
  uint64_t *x3 = x + 3U;
  uint8_t b1 = LongSubtraction_sub_borrow(b0, *x0, y[0U], dst0);
  uint8_t b2 = LongSubtraction_sub_borrow(b1, *x1, y[1U], dst1);
  uint8_t b3 = LongSubtraction_sub_borrow(b2, *x2, y[2U], dst2);
  uint8_t b4 = LongSubtraction_sub_borrow(b3, *x3, y[3U], dst3);
  return b4;
}

