/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/everest/karamel/krml LongSubtraction.fst -add-include <immintrin.h> -skip-compilation
  F* version: <unknown>
  KaRaMeL version: 442927db
 */

#ifndef __LongSubtraction_H
#define __LongSubtraction_H

#include "krmllib.h"

#include <immintrin.h>

typedef krml_checked_int_t LongSubtraction_t;

typedef uint64_t *LongSubtraction_s;

typedef uint8_t LongSubtraction_borrow;

#define LongSubtraction_sub_borrow _subborrow_u64

extern uint8_t LongSubtraction_sub_borrow(uint8_t b_in, uint64_t x, uint64_t y, uint64_t *ret);

uint8_t LongSubtraction_sub(uint64_t *dst, uint64_t *x, uint64_t *y, uint8_t b0);


#define __LongSubtraction_H_DEFINED
#endif
